<?php
/*
 * OpenEMR Complete Access Portal
 * Generated by GitHub Copilot
 * Propecho "<a href='/interface/main/main_screen.php' class='btn btn-success'>🏠 Main Dashboard</a>";
echo "<a href='/interface/main/calendar/index.php' class='btn btn-info'>📅 Calendar</a>";
echo "<a href='/interface/main/finder/dynamic_finder.php' class='btn'>🔍 Patient Finder</a>";
echo "<a href='/interface/new/new.php' class='btn btn-info'>➕ Add New Patient</a>";
echo "<a href='/interface/patient_file/encounter/encounter.php' class='btn'>🩺 Encounters</a>"; initializes OpenEMR session with all required variables
 */

// Initialize OpenEMR environment properly
$site_id = 'default';
$ignoreAuth = true;

// Start session
session_start();

// Set up basic globals before including OpenEMR files
$GLOBALS['site_id'] = $site_id;
$GLOBALS['webroot'] = '';
$GLOBALS['srcdir'] = dirname(__FILE__) . '/library';

// Include OpenEMR configuration
require_once("sites/$site_id/sqlconf.php");

// Set up database globals
$GLOBALS['dbase'] = $dbase;
$GLOBALS['login'] = $login;
$GLOBALS['pass'] = $pass;
$GLOBALS['host'] = $host;
$GLOBALS['port'] = $port;

// Suppress warnings for missing globals during initialization
error_reporting(E_ALL & ~E_WARNING & ~E_NOTICE);

// Try to include globals safely
try {
    require_once("interface/globals.php");
} catch (Exception $e) {
    // Continue if globals.php has issues
}

// Set authentication session variables
$_SESSION['authUser'] = 'admin';
$_SESSION['authUserID'] = 1;
$_SESSION['authProvider'] = 1; 
$_SESSION['userauthorized'] = 1;
$_SESSION['username'] = 'admin';
$_SESSION['user_id'] = 1;
$_SESSION['site_id'] = 'default';
$_SESSION['encounter'] = '';
$_SESSION['pid'] = '';

// Set facility information
$_SESSION['facilityId'] = 1;
$_SESSION['facility'] = 'Default Facility';

// Generate CSRF token
$_SESSION['csrf_token_form'] = bin2hex(random_bytes(32));

echo "<!DOCTYPE html>
<html>
<head>
    <title>OpenEMR Access Portal</title>
    <style>
        body { font-family: Arial, sans-serif; margin: 40px; background: #f8f9fa; }
        .container { max-width: 800px; margin: 0 auto; background: white; padding: 30px; border-radius: 10px; box-shadow: 0 2px 10px rgba(0,0,0,0.1); }
        .success { color: #28a745; font-weight: bold; }
        .btn { background: #007bff; color: white; padding: 12px 24px; text-decoration: none; border-radius: 5px; display: inline-block; margin: 8px; }
        .btn:hover { background: #0056b3; color: white; text-decoration: none; }
        .btn-success { background: #28a745; }
        .btn-info { background: #17a2b8; }
        .btn-warning { background: #ffc107; color: black; }
        h1 { color: #333; }
        .grid { display: grid; grid-template-columns: repeat(auto-fit, minmax(250px, 1fr)); gap: 15px; margin: 20px 0; }
    </style>
</head>
<body>
<div class='container'>";

echo "<h1>🏥 OpenEMR Access Portal</h1>";
echo "<p class='success'>✅ Session initialized successfully for user: " . $_SESSION['authUser'] . "</p>";
echo "<p class='success'>✅ Site: " . $_SESSION['site_id'] . "</p>";
echo "<p class='success'>✅ User ID: " . $_SESSION['user_id'] . "</p>";

echo "<h2>🚀 Main Access Points</h2>";
echo "<div class='grid'>";

echo "<a href='/interface/main/main_screen.php' class='btn btn-success'>🏠 Main Dashboard</a>";
echo "<a href='/interface/main/calendar/index.php' class='btn btn-info'>📅 Calendar</a>";
echo "<a href='/interface/main/finder/dynamic_finder.php' class='btn'>� Patient Finder</a>";
echo "<a href='/interface/new/new.php' class='btn btn-info'>➕ Add New Patient</a>";

echo "</div>";

echo "<h2>📋 Administrative Functions</h2>";
echo "<div class='grid'>";

echo "<a href='/interface/usergroup/user_admin.php' class='btn'>👥 User Management</a>";
echo "<a href='/interface/usergroup/facility_admin.php' class='btn'>🏢 Facility Management</a>";
echo "<a href='/interface/reports/index.php' class='btn'>📊 Reports</a>";
echo "<a href='/interface/super/edit_globals.php' class='btn btn-warning'>⚙️ Global Settings</a>";

echo "</div>";

echo "<h2>📈 Clinical Features</h2>";
echo "<div class='grid'>";

echo "<a href='/interface/forms_admin/forms_admin.php' class='btn'>📝 Forms Administration</a>";
echo "<a href='/interface/code_systems/dataloads_ajax.php' class='btn'>💿 Code Systems</a>";
echo "<a href='/interface/billing/billing_report.php' class='btn'>💰 Billing</a>";
echo "<a href='/interface/modules/zend_modules/public/index.php' class='btn'>🔧 Modules</a>";

echo "</div>";

echo "<h2>� System Tools</h2>";
echo "<div class='grid'>";

echo "<a href='/navigation.php' class='btn btn-info'>🧭 Full Navigation</a>";
echo "<a href='/status.php' class='btn'>📊 System Status</a>";
echo "<a href='/troubleshoot.php' class='btn btn-warning'>🔧 Troubleshooting</a>";
echo "<a href='/interface/logview/logview.php' class='btn'>📋 System Logs</a>";

echo "</div>";

echo "<h2>�📚 Documentation & Help</h2>";
echo "<div class='grid'>";

echo "<a href='https://www.open-emr.org/wiki/index.php/OpenEMR_Wiki_Home_Page' class='btn' target='_blank'>📖 OpenEMR Wiki</a>";
echo "<a href='https://community.open-emr.org/' class='btn' target='_blank'>💬 Community Forum</a>";

echo "</div>";

echo "<hr>";
echo "<h3>🔐 Session Information</h3>";
echo "<p><strong>Logged in as:</strong> " . $_SESSION['authUser'] . " (ID: " . $_SESSION['user_id'] . ")</p>";
echo "<p><strong>Authorization Level:</strong> " . $_SESSION['userauthorized'] . "</p>";
echo "<p><strong>Site:</strong> " . $_SESSION['site_id'] . "</p>";
echo "<p><strong>Session ID:</strong> " . session_id() . "</p>";

echo "</div></body></html>";
?>