<?php
/*
 * PHP Configuration Check for OpenEMR
 * Generated by GitHub Copilot
 */

echo "<h2>PHP Configuration Analysis for OpenEMR</h2>\n";

echo "<h3>Current PHP Information:</h3>\n";
echo "<ul>\n";
echo "<li><strong>PHP Version:</strong> " . PHP_VERSION . "</li>\n";
echo "<li><strong>PHP INI File:</strong> " . php_ini_loaded_file() . "</li>\n";
echo "</ul>\n";

echo "<h3>Required Extensions Check:</h3>\n";

$required_extensions = [
    'mysqli' => 'MySQL Improved Extension (required for OpenEMR database)',
    'pdo' => 'PDO Extension (alternative database support)',
    'pdo_mysql' => 'PDO MySQL Driver',
    'mysqlnd' => 'MySQL Native Driver',
    'openssl' => 'OpenSSL (for security)',
    'curl' => 'cURL (for HTTP requests)',
    'gd' => 'GD Graphics Library',
    'mbstring' => 'Multibyte String Functions',
    'xml' => 'XML Parser',
    'zip' => 'ZIP Archive',
    'json' => 'JSON Functions'
];

echo "<table border='1' style='border-collapse: collapse; width: 100%;'>\n";
echo "<tr><th>Extension</th><th>Status</th><th>Description</th></tr>\n";

foreach ($required_extensions as $ext => $desc) {
    $loaded = extension_loaded($ext);
    $status = $loaded ? 
        "<span style='color: green;'>✓ Loaded</span>" : 
        "<span style='color: red;'>✗ Missing</span>";
    
    echo "<tr>\n";
    echo "<td><strong>$ext</strong></td>\n";
    echo "<td>$status</td>\n";
    echo "<td>$desc</td>\n";
    echo "</tr>\n";
}
echo "</table>\n";

echo "<h3>PHP INI File Contents (MySQL-related):</h3>\n";
$ini_file = php_ini_loaded_file();
if ($ini_file && file_exists($ini_file)) {
    echo "<p><strong>INI File:</strong> " . htmlspecialchars($ini_file) . "</p>\n";
    
    $ini_content = file_get_contents($ini_file);
    $lines = explode("\n", $ini_content);
    
    echo "<h4>MySQL/MySQLi Related Configuration:</h4>\n";
    echo "<pre style='background: #f4f4f4; padding: 10px; border-radius: 4px; max-height: 300px; overflow-y: scroll;'>\n";
    
    foreach ($lines as $line_num => $line) {
        $line = trim($line);
        if (stripos($line, 'mysql') !== false || stripos($line, 'pdo') !== false) {
            echo sprintf("%04d: %s\n", $line_num + 1, htmlspecialchars($line));
        }
    }
    echo "</pre>\n";
} else {
    echo "<p style='color: red;'>Could not locate or read PHP INI file.</p>\n";
}

echo "<h3>Solution Steps:</h3>\n";
echo "<ol>\n";
echo "<li><strong>Enable MySQLi Extension:</strong></li>\n";
echo "<ul>\n";
echo "<li>Edit your PHP ini file: <code>" . htmlspecialchars($ini_file) . "</code></li>\n";
echo "<li>Find the line <code>;extension=mysqli</code> and uncomment it by removing the semicolon: <code>extension=mysqli</code></li>\n";
echo "<li>Save the file and restart your web server</li>\n";
echo "</ul>\n";

echo "<li><strong>Alternative - Enable via Command:</strong></li>\n";
echo "<ul>\n";
echo "<li>You can also try enabling it temporarily by adding this to a test PHP file:</li>\n";
echo "<li><code>dl('mysqli.dll');</code> (Windows) or <code>dl('mysqli.so');</code> (Linux)</li>\n";
echo "</ul>\n";

echo "<li><strong>Check Extension Directory:</strong></li>\n";
echo "<ul>\n";
echo "<li>Extension directory: <code>" . ini_get('extension_dir') . "</code></li>\n";
echo "<li>Make sure <code>php_mysqli.dll</code> (Windows) exists in the extension directory</li>\n";
echo "</ul>\n";
echo "</ol>\n";

// Check if extension directory exists and contains mysqli
$ext_dir = ini_get('extension_dir');
echo "<h3>Extension Directory Analysis:</h3>\n";
echo "<p><strong>Extension Directory:</strong> " . htmlspecialchars($ext_dir) . "</p>\n";

if (is_dir($ext_dir)) {
    $files = scandir($ext_dir);
    $mysqli_files = array_filter($files, function($file) {
        return stripos($file, 'mysqli') !== false;
    });
    
    if (!empty($mysqli_files)) {
        echo "<p style='color: green;'>✓ MySQLi extension files found:</p>\n";
        echo "<ul>\n";
        foreach ($mysqli_files as $file) {
            echo "<li>" . htmlspecialchars($file) . "</li>\n";
        }
        echo "</ul>\n";
    } else {
        echo "<p style='color: red;'>✗ No MySQLi extension files found in extension directory.</p>\n";
    }
} else {
    echo "<p style='color: red;'>✗ Extension directory does not exist or is not accessible.</p>\n";
}

?>