<?php
/*
 * Login Debug Test
 * Generated by GitHub Copilot
 * Tests the exact login process
 */

// Load OpenEMR configuration
$site_id = 'default';
require_once("sites/$site_id/sqlconf.php");

echo "=== OpenEMR Login Debug Test ===\n\n";

// Test database connection
$connection = mysqli_connect($host, $login, $pass, $dbase, $port);
if (!$connection) {
    die("Database connection failed: " . mysqli_connect_error() . "\n");
}

echo "✅ Database connected successfully\n";

// Test user lookup with exact query OpenEMR would use
$username = 'admin';
$test_password = 'pass';

echo "Testing login for username: '$username'\n";
echo "Testing password: '$test_password'\n\n";

// Query exactly like OpenEMR does
$query = "SELECT u.*, us.password FROM users u LEFT JOIN users_secure us ON u.id = us.id WHERE u.username = ? AND u.active = 1";
$stmt = mysqli_prepare($connection, $query);
mysqli_stmt_bind_param($stmt, 's', $username);
mysqli_stmt_execute($stmt);
$result = mysqli_stmt_get_result($stmt);

if ($user = mysqli_fetch_assoc($result)) {
    echo "✅ User found in database:\n";
    echo "   - ID: " . $user['id'] . "\n";
    echo "   - Username: " . $user['username'] . "\n";
    echo "   - Full Name: " . $user['fname'] . " " . $user['lname'] . "\n";
    echo "   - Active: " . ($user['active'] ? 'Yes' : 'No') . "\n";
    echo "   - Authorized: " . ($user['authorized'] ? 'Yes' : 'No') . "\n";
    echo "   - Password hash: " . substr($user['password'], 0, 20) . "...\n\n";
    
    // Test password verification
    if (password_verify($test_password, $user['password'])) {
        echo "✅ PASSWORD VERIFICATION SUCCESSFUL!\n";
        echo "✅ Login should work with: username='admin', password='pass'\n\n";
        
        // Additional checks
        if ($user['authorized'] == 1) {
            echo "✅ User is authorized\n";
        } else {
            echo "❌ User is not authorized (authorized = " . $user['authorized'] . ")\n";
        }
        
        if ($user['active'] == 1) {
            echo "✅ User is active\n";
        } else {
            echo "❌ User is not active (active = " . $user['active'] . ")\n";
        }
        
    } else {
        echo "❌ PASSWORD VERIFICATION FAILED!\n";
        echo "The password 'pass' does not match the stored hash.\n";
        
        // Let's regenerate the password hash
        echo "\nRegenerating password hash...\n";
        $new_hash = password_hash($test_password, PASSWORD_DEFAULT);
        echo "New hash: " . $new_hash . "\n";
        
        // Update the password
        $update_query = "UPDATE users_secure SET password = ? WHERE id = ?";
        $update_stmt = mysqli_prepare($connection, $update_query);
        mysqli_stmt_bind_param($update_stmt, 'si', $new_hash, $user['id']);
        
        if (mysqli_stmt_execute($update_stmt)) {
            echo "✅ Password updated in database\n";
            
            // Test again
            if (password_verify($test_password, $new_hash)) {
                echo "✅ Password verification now works!\n";
            }
        } else {
            echo "❌ Failed to update password\n";
        }
    }
    
} else {
    echo "❌ User 'admin' not found or not active\n";
}

echo "\n=== Login Instructions ===\n";
echo "URL: https://ddns.badgertechnologies.us/interface/login/login.php?site=default\n";
echo "Username: admin\n";
echo "Password: pass\n";

mysqli_close($connection);
?>