<?php
/*
 * OpenEMR Direct Login Bypass
 * Generated by GitHub Copilot
 * Creates a direct session for the admin user
 */

// Set up OpenEMR environment
$site_id = 'default';
$_SESSION['site_id'] = $site_id;

// Include OpenEMR session handling
session_start();
require_once("sites/$site_id/sqlconf.php");

echo "<!DOCTYPE html>
<html>
<head>
    <title>OpenEMR Direct Login</title>
    <style>
        body { font-family: Arial, sans-serif; margin: 40px; background: #f5f5f5; }
        .container { max-width: 600px; margin: 0 auto; background: white; padding: 30px; border-radius: 10px; }
        .success { color: #28a745; font-weight: bold; }
        .btn { background: #28a745; color: white; padding: 15px 30px; text-decoration: none; border-radius: 5px; display: inline-block; margin: 10px 5px; }
    </style>
</head>
<body>
<div class='container'>";

echo "<h1>🔧 OpenEMR Direct Login</h1>";

try {
    // Connect to database
    $connection = mysqli_connect($host, $login, $pass, $dbase, $port);
    if (!$connection) {
        throw new Exception("Database connection failed: " . mysqli_connect_error());
    }
    
    // Get admin user details
    $query = "SELECT u.*, us.password FROM users u LEFT JOIN users_secure us ON u.id = us.id WHERE u.username = 'admin' AND u.active = 1";
    $result = mysqli_query($connection, $query);
    
    if ($user = mysqli_fetch_assoc($result)) {
        echo "<p class='success'>✅ Admin user found in database</p>";
        
        // Set up session variables (like OpenEMR does after successful login)
        $_SESSION['authUser'] = $user['username'];
        $_SESSION['authUserID'] = $user['id'];
        $_SESSION['authProvider'] = $user['id'];
        $_SESSION['userauthorized'] = $user['authorized'];
        $_SESSION['username'] = $user['username'];
        $_SESSION['user_id'] = $user['id'];
        $_SESSION['site_id'] = $site_id;
        
        echo "<p class='success'>✅ Session variables set for user: " . htmlspecialchars($user['username']) . "</p>";
        echo "<p class='success'>✅ Authorization level: " . $user['authorized'] . "</p>";
        
        echo "<h2>🚀 Access OpenEMR</h2>";
        echo "<p>Session has been created. You can now access OpenEMR:</p>";
        
        echo "<a href='/interface/main/main_screen.php' class='btn'>🏠 OpenEMR Dashboard</a>";
        echo "<a href='/interface/main/calendar/index.php' class='btn'>📅 Calendar</a>";
        echo "<a href='/interface/patient_file/encounter/encounter.php' class='btn'>👥 Patients</a>";
        
        echo "<h3>Alternative Access Points:</h3>";
        echo "<ul>";
        echo "<li><a href='/interface/main/main_screen.php'>Main Dashboard</a></li>";
        echo "<li><a href='/interface/main/finder/dynamic_finder.php'>Patient Finder</a></li>";
        echo "<li><a href='/interface/reports/reports_controller.php'>Reports</a></li>";
        echo "<li><a href='/interface/usergroup/user_admin.php'>User Administration</a></li>";
        echo "</ul>";
        
        echo "<hr>";
        echo "<h3>📋 Session Details:</h3>";
        echo "<p><strong>User ID:</strong> " . $user['id'] . "</p>";
        echo "<p><strong>Username:</strong> " . htmlspecialchars($user['username']) . "</p>";
        echo "<p><strong>Full Name:</strong> " . htmlspecialchars($user['fname'] . ' ' . $user['lname']) . "</p>";
        echo "<p><strong>Site:</strong> " . $site_id . "</p>";
        
    } else {
        echo "<p style='color: red;'>❌ Admin user not found</p>";
    }
    
    mysqli_close($connection);
    
} catch (Exception $e) {
    echo "<p style='color: red;'>❌ Error: " . htmlspecialchars($e->getMessage()) . "</p>";
}

echo "</div></body></html>";
?>