<?php
/*
 * OpenEMR Quick Navigation
 * Generated by GitHub Copilot
 * Provides quick access to commonly used OpenEMR functions
 */

// Set up OpenEMR environment
$site_id = 'default';
$ignoreAuth = true;
session_start();

// Set required session variables
$_SESSION['authUser'] = 'admin';
$_SESSION['authUserID'] = 1;
$_SESSION['authProvider'] = 1; 
$_SESSION['userauthorized'] = 1;
$_SESSION['username'] = 'admin';
$_SESSION['user_id'] = 1;
$_SESSION['site_id'] = 'default';

echo "<!DOCTYPE html>
<html>
<head>
    <title>OpenEMR Quick Navigation</title>
    <style>
        body { font-family: Arial, sans-serif; margin: 20px; background: #f8f9fa; }
        .nav-container { max-width: 1200px; margin: 0 auto; }
        .nav-section { background: white; margin: 15px 0; padding: 20px; border-radius: 8px; box-shadow: 0 2px 4px rgba(0,0,0,0.1); }
        .nav-grid { display: grid; grid-template-columns: repeat(auto-fit, minmax(200px, 1fr)); gap: 10px; }
        .nav-btn { 
            background: #007bff; color: white; padding: 10px 15px; text-decoration: none; 
            border-radius: 4px; display: block; text-align: center; transition: background 0.2s;
        }
        .nav-btn:hover { background: #0056b3; color: white; text-decoration: none; }
        .nav-btn.success { background: #28a745; }
        .nav-btn.info { background: #17a2b8; }
        .nav-btn.warning { background: #ffc107; color: black; }
        .nav-btn.danger { background: #dc3545; }
        h2 { color: #333; margin-bottom: 15px; border-bottom: 2px solid #007bff; padding-bottom: 5px; }
        h1 { text-align: center; color: #333; }
    </style>
</head>
<body>
<div class='nav-container'>";

echo "<h1>🚀 OpenEMR Quick Navigation</h1>";

// Main Functions
echo "<div class='nav-section'>";
echo "<h2>🏠 Main Functions</h2>";
echo "<div class='nav-grid'>";
echo "<a href='/interface/main/main_screen.php' class='nav-btn success'>Main Dashboard</a>";
echo "<a href='/interface/main/calendar/index.php' class='nav-btn info'>Calendar</a>";
echo "<a href='/interface/main/finder/dynamic_finder.php' class='nav-btn'>Patient Finder</a>";
echo "<a href='/interface/new/new.php' class='nav-btn success'>New Patient</a>";
echo "<a href='/interface/patient_file/encounter/encounter.php' class='nav-btn'>Encounters</a>";
echo "<a href='/interface/main/tabs/main.php' class='nav-btn'>Patient Tabs</a>";
echo "</div></div>";

// Administrative
echo "<div class='nav-section'>";
echo "<h2>⚙️ Administration</h2>";
echo "<div class='nav-grid'>";
echo "<a href='/interface/usergroup/user_admin.php' class='nav-btn'>User Management</a>";
echo "<a href='/interface/usergroup/facility_admin.php' class='nav-btn'>Facilities</a>";
echo "<a href='/interface/super/edit_globals.php' class='nav-btn warning'>Global Settings</a>";
echo "<a href='/interface/usergroup/addrbook_admin.php' class='nav-btn'>Address Book</a>";
echo "<a href='/interface/forms_admin/forms_admin.php' class='nav-btn'>Forms Admin</a>";
echo "<a href='/interface/super/rules/index.php' class='nav-btn'>Clinical Rules</a>";
echo "</div></div>";

// Clinical
echo "<div class='nav-section'>";
echo "<h2>🩺 Clinical</h2>";
echo "<div class='nav-grid'>";
echo "<a href='/interface/patient_file/encounter/forms.php' class='nav-btn info'>Encounter Forms</a>";
echo "<a href='/interface/patient_file/encounter/diagnosis.php' class='nav-btn info'>Diagnosis</a>";
echo "<a href='/interface/orders/orders_results.php' class='nav-btn'>Lab Results</a>";
echo "<a href='/interface/drugs/drug_inventory.php' class='nav-btn'>Drug Inventory</a>";
echo "<a href='/interface/patient_tracker/patient_tracker.php' class='nav-btn'>Patient Flow</a>";
echo "<a href='/interface/therapy_groups/index.php' class='nav-btn'>Therapy Groups</a>";
echo "</div></div>";

// Reports & Billing
echo "<div class='nav-section'>";
echo "<h2>📊 Reports & Billing</h2>";
echo "<div class='nav-grid'>";
echo "<a href='/interface/reports/index.php' class='nav-btn'>Reports</a>";
echo "<a href='/interface/billing/billing_report.php' class='nav-btn warning'>Billing</a>";
echo "<a href='/interface/billing/sl_eob_search.php' class='nav-btn warning'>EOB Processing</a>";
echo "<a href='/interface/reports/appointments_report.php' class='nav-btn'>Appointments Report</a>";
echo "<a href='/interface/reports/financial_summary_report.php' class='nav-btn'>Financial Summary</a>";
echo "<a href='/interface/reports/immunization_report.php' class='nav-btn'>Immunizations</a>";
echo "</div></div>";

// System Tools
echo "<div class='nav-section'>";
echo "<h2>🔧 System Tools</h2>";
echo "<div class='nav-grid'>";
echo "<a href='/interface/code_systems/dataloads_ajax.php' class='nav-btn'>Code Systems</a>";
echo "<a href='/interface/modules/zend_modules/public/index.php' class='nav-btn'>Modules</a>";
echo "<a href='/interface/logview/logview.php' class='nav-btn'>System Logs</a>";
echo "<a href='/interface/language/language.php' class='nav-btn'>Language Settings</a>";
echo "<a href='/interface/super/show_credits.php' class='nav-btn'>Credits</a>";
echo "<a href='/sql_upgrade.php' class='nav-btn danger'>Database Upgrade</a>";
echo "</div></div>";

// Quick Access Tools
echo "<div class='nav-section'>";
echo "<h2>⚡ Quick Access</h2>";
echo "<div class='nav-grid'>";
echo "<a href='/access_portal.php' class='nav-btn success'>Access Portal</a>";
echo "<a href='/status.php' class='nav-btn info'>System Status</a>";
echo "<a href='/troubleshoot.php' class='nav-btn warning'>Troubleshooting</a>";
echo "<a href='/interface/login/login.php?site=default' class='nav-btn'>Login Page</a>";
echo "<a href='javascript:history.back()' class='nav-btn'>← Go Back</a>";
echo "<a href='javascript:location.reload()' class='nav-btn'>🔄 Refresh</a>";
echo "</div></div>";

echo "</div></body></html>";
?>