<?php
/*
 * OpenEMR Quick Access (Updated)
 * Generated by GitHub Copilot  
 * Simple entry point to OpenEMR with proper site setup
 */

// Set up session and redirect to main interface
session_start();

// Set all required session variables for OpenEMR access
$_SESSION['authUser'] = 'admin';
$_SESSION['authUserID'] = '1';
$_SESSION['authProvider'] = '1'; 
$_SESSION['userauthorized'] = '1';
$_SESSION['username'] = 'admin';
$_SESSION['user_id'] = '1';
$_SESSION['site_id'] = 'default';

// Additional session variables that OpenEMR needs
$_SESSION['encounter'] = '';
$_SESSION['pid'] = '';
$_SESSION['facilityId'] = '1';
$_SESSION['facility'] = 'Your Clinic Name Here';
$_SESSION['csrf_token_form'] = bin2hex(random_bytes(32));

// Set globals for site configuration
$GLOBALS['site_id'] = 'default';
$site_id = 'default';

// Redirect to OpenEMR main interface
header('Location: /interface/main/main_screen.php');
exit();
?>