-- OpenEMR Admin User Reset Script
-- Generated by GitHub Copilot

USE openemr;

-- Check for existing admin users
SELECT 'Checking existing users:' as status;
SELECT id, username, active FROM users WHERE username IN ('admin', 'openemr_admin');

-- Delete any existing admin users to start fresh
DELETE FROM users_secure WHERE id IN (SELECT id FROM users WHERE username IN ('admin', 'openemr_admin'));
DELETE FROM users WHERE username IN ('admin', 'openemr_admin');

-- Create new admin user
INSERT INTO users (
    username, 
    fname, 
    lname, 
    authorized, 
    active, 
    calendar, 
    see_auth,
    password
) VALUES (
    'admin', 
    'Administrator', 
    'OpenEMR', 
    1, 
    1, 
    1, 
    1,
    'NoLongerUsed'
);

-- Get the new user ID
SET @user_id = LAST_INSERT_ID();

-- Set password in users_secure table (password = 'pass')
INSERT INTO users_secure (id, username, password) 
VALUES (@user_id, 'admin', '$2a$05$MKtnxYsfFPlb2mOW7Qzq2Oz61S26s5E80Yd60lKdX4Wy3PBdEufNu');

-- Verify the user was created
SELECT 'New admin user created:' as status;
SELECT u.id, u.username, u.active, us.username as secure_username 
FROM users u 
LEFT JOIN users_secure us ON u.id = us.id 
WHERE u.username = 'admin';

SELECT 'Setup complete! Use username: admin, password: pass' as result;