<?php
/*
 * OpenEMR Session Reset
 * Generated by GitHub Copilot
 * Clears any problematic sessions
 */

echo "<!DOCTYPE html><html><head><title>Session Reset</title></head><body>";
echo "<h1>OpenEMR Session Reset</h1>";

// Start session and destroy it
session_start();
session_destroy();
session_write_close();

// Clear any session cookies
if (isset($_COOKIE[session_name()])) {
    setcookie(session_name(), '', time()-3600, '/');
}

echo "<p style='color: green;'>✅ Session cleared successfully!</p>";
echo "<p><a href='/interface/login/login.php?site=default' style='background: #007bff; color: white; padding: 10px 20px; text-decoration: none; border-radius: 4px;'>Try Login Again</a></p>";
echo "</body></html>";
?>