-- Test Insurance Setup Script for OpenEMR Auto-Billing
-- Generated by GitHub Copilot
-- Run this in your OpenEMR MySQL database to create test insurance

-- Insert Test Insurance Company
INSERT INTO insurance_companies (
    name, 
    attn, 
    cms_id, 
    freeb_type, 
    x12_receiver_id, 
    x12_default_partner_id,
    address_line1,
    city,
    state,
    zip,
    phone,
    fax
) VALUES (
    'BadgerCare Insurance Company',
    'Claims Processing Department',
    'BC001',
    0,
    'BC001',
    1,
    '123 Insurance Way',
    'Healthcare City',
    'TX',
    '75001',
    '5551234567',
    '5551234568'
);

-- Get the insurance company ID for reference
SET @insurance_company_id = LAST_INSERT_ID();

-- Insert Test Insurance Plan/Type
INSERT INTO insurance_type_codes (
    type, 
    code, 
    modifier, 
    units
) VALUES (
    'BadgerCare Premium Plan',
    'BC-PREM',
    '',
    1
);

-- Insert Test Patient (if needed)
INSERT INTO patient_data (
    fname,
    lname,
    DOB,
    sex,
    ss,
    street,
    city,
    state,
    postal_code,
    phone_home,
    pid
) VALUES (
    'TestPatient',
    'AutoBilling',
    '1985-05-15',
    'Male',
    '123456789',
    '789 Test Street',
    'Test City',
    'TX',
    '75003',
    '5559876543',
    (SELECT COALESCE(MAX(pid), 0) + 1 FROM patient_data p)
);

-- Get the patient ID
SET @patient_id = LAST_INSERT_ID();

-- Insert Primary Insurance for Test Patient
INSERT INTO insurance_data (
    pid,
    type,
    provider,
    plan_name,
    policy_number,
    group_number,
    subscriber_lname,
    subscriber_fname,
    subscriber_relationship,
    subscriber_ss,
    subscriber_DOB,
    subscriber_street,
    subscriber_city,
    subscriber_state,
    subscriber_postal_code,
    subscriber_phone,
    copay,
    date
) VALUES (
    @patient_id,
    'primary',
    @insurance_company_id,
    'BadgerCare Premium Plan',
    'BC-POL-123456',
    'BC-GRP-001',
    'AutoBilling',
    'TestPatient',
    'self',
    '123456789',
    '1985-05-15',
    '789 Test Street',
    'Test City',
    'TX',
    '75003',
    '5559876543',
    '25.00',
    CURDATE()
);

-- Display results
SELECT 'Test Insurance Company Created:' as Result;
SELECT id, name, cms_id FROM insurance_companies WHERE name = 'BadgerCare Insurance Company';

SELECT 'Test Patient Created:' as Result;
SELECT pid, fname, lname, DOB FROM patient_data WHERE fname = 'TestPatient' AND lname = 'AutoBilling';

SELECT 'Patient Insurance Assigned:' as Result;
SELECT pid, type, policy_number, group_number FROM insurance_data WHERE pid = @patient_id;