<?php
/*
 * Quick Status Check for OpenEMR Dashboard
 * Generated by GitHub Copilot
 */
echo "OpenEMR Dashboard Status: ONLINE\n";
echo "Server Time: " . date('Y-m-d H:i:s') . "\n";
echo "PHP Version: " . phpversion() . "\n";
echo "Server: " . $_SERVER['SERVER_NAME'] . ":" . $_SERVER['SERVER_PORT'] . "\n";
?>