<?php
/*
 * OpenEMR Status Page
 * Generated by GitHub Copilot  
 * Final verification that everything is working
 */

echo "<!DOCTYPE html>
<html>
<head>
    <title>OpenEMR Status Check</title>
    <style>
        body { font-family: Arial, sans-serif; margin: 40px; }
        .success { color: green; }
        .error { color: red; }
        .info { color: blue; }
    </style>
</head>
<body>";

echo "<h1>OpenEMR Installation Status</h1>";

// Check 1: Composer Dependencies
echo "<h2>1. Dependencies Check</h2>";
if (file_exists(__DIR__ . '/vendor/autoload.php')) {
    echo "<p class='success'>✅ Composer dependencies installed</p>";
    require_once __DIR__ . '/vendor/autoload.php';
    echo "<p class='success'>✅ Autoloader working</p>";
} else {
    echo "<p class='error'>❌ Composer dependencies missing</p>";
}

// Check 2: Database Connection  
echo "<h2>2. Database Connection</h2>";
$site_id = 'default';
if (file_exists("sites/$site_id/sqlconf.php")) {
    require_once("sites/$site_id/sqlconf.php");
    try {
        $connection = mysqli_connect($host, $login, $pass, $dbase, $port);
        if ($connection) {
            echo "<p class='success'>✅ Database connection successful</p>";
            echo "<p class='info'>Host: $host:$port</p>";
            echo "<p class='info'>Database: $dbase</p>";
            echo "<p class='info'>User: $login</p>";
            mysqli_close($connection);
        } else {
            echo "<p class='error'>❌ Database connection failed</p>";
        }
    } catch (Exception $e) {
        echo "<p class='error'>❌ Database error: " . $e->getMessage() . "</p>";
    }
} else {
    echo "<p class='error'>❌ Database configuration missing</p>";
}

// Check 3: Configuration
echo "<h2>3. OpenEMR Configuration</h2>";
if (isset($config) && $config == 1) {
    echo "<p class='success'>✅ OpenEMR configured ($config)</p>";
} else {
    echo "<p class='error'>❌ OpenEMR not configured</p>";
}

// Check 4: Login Test
echo "<h2>4. Login Credentials Test</h2>";
if (isset($connection) && $connection) {
    $connection = mysqli_connect($host, $login, $pass, $dbase, $port);
    $query = "SELECT COUNT(*) as count FROM users WHERE username = 'admin' AND active = 1";
    $result = mysqli_query($connection, $query);
    if ($result && $row = mysqli_fetch_assoc($result)) {
        if ($row['count'] > 0) {
            echo "<p class='success'>✅ Admin user exists and is active</p>";
        } else {
            echo "<p class='error'>❌ Admin user not found or inactive</p>";
        }
    }
    mysqli_close($connection);
}

echo "<h2>5. Access Information</h2>";
echo "<div style='background: #f0f0f0; padding: 20px; border-radius: 8px;'>";
echo "<h3>Local Access:</h3>";
echo "<p><strong>URL:</strong> <a href='/interface/login/login.php?site=default' target='_blank'>http://127.0.0.1:8080/interface/login/login.php?site=default</a></p>";
echo "<p><strong>Username:</strong> admin</p>";  
echo "<p><strong>Password:</strong> pass</p>";

echo "<h3>Cloudflare Tunnel Access:</h3>";
echo "<p><strong>URL:</strong> <a href='https://ddns.badgertechnologies.us/interface/login/login.php?site=default' target='_blank'>https://ddns.badgertechnologies.us/interface/login/login.php?site=default</a></p>";
echo "<p><strong>Username:</strong> admin</p>";
echo "<p><strong>Password:</strong> pass</p>";
echo "</div>";

echo "<h2>6. Quick Test</h2>";
echo "<p><a href='/interface/login/login.php?site=default' style='background: #007cba; color: white; padding: 10px 20px; text-decoration: none; border-radius: 4px;'>Test OpenEMR Login →</a></p>";

echo "</body></html>";
?>