<?php
/*
 * Simple test file
 * Generated by GitHub Copilot
 * Tests if vendor/autoload.php is accessible
 */
echo "<h1>OpenEMR Dependency Test</h1>\n";

if (file_exists(__DIR__ . '/vendor/autoload.php')) {
    echo "<p style='color: green;'>✓ vendor/autoload.php exists</p>\n";
    
    try {
        require_once __DIR__ . '/vendor/autoload.php';
        echo "<p style='color: green;'>✓ Composer autoloader loaded successfully</p>\n";
    } catch (Exception $e) {
        echo "<p style='color: red;'>✗ Error loading autoloader: " . $e->getMessage() . "</p>\n";
    }
} else {
    echo "<p style='color: red;'>✗ vendor/autoload.php not found</p>\n";
}

echo "<p><a href='/interface/login/login.php?site=default'>Test OpenEMR Login</a></p>\n";
?>