<?php
/*
 * OpenEMR Login Test Script
 * Generated by GitHub Copilot
 * Tests the login functionality directly
 */

// Load OpenEMR configuration
$site_id = 'default';
require_once("sites/$site_id/sqlconf.php");

echo "<h2>OpenEMR Login Test</h2>\n";

// Test database connection
echo "<h3>1. Database Connection Test:</h3>\n";
try {
    $connection = mysqli_connect($host, $login, $pass, $dbase, $port);
    if ($connection) {
        echo "<p style='color: green;'>✓ Database connection successful</p>\n";
    } else {
        echo "<p style='color: red;'>✗ Database connection failed: " . mysqli_connect_error() . "</p>\n";
        exit;
    }
} catch (Exception $e) {
    echo "<p style='color: red;'>✗ Database connection error: " . $e->getMessage() . "</p>\n";
    exit;
}

// Test user lookup
echo "<h3>2. User Lookup Test:</h3>\n";
$test_username = 'admin';
$user_query = "SELECT u.id, u.username, u.fname, u.lname, u.authorized, u.active, us.password 
               FROM users u 
               LEFT JOIN users_secure us ON u.id = us.id 
               WHERE u.username = ?";

$stmt = mysqli_prepare($connection, $user_query);
mysqli_stmt_bind_param($stmt, 's', $test_username);
mysqli_stmt_execute($stmt);
$result = mysqli_stmt_get_result($stmt);

if ($user = mysqli_fetch_assoc($result)) {
    echo "<p style='color: green;'>✓ User found: " . htmlspecialchars($user['username']) . "</p>\n";
    echo "<p>User ID: " . $user['id'] . "</p>\n";
    echo "<p>Full Name: " . htmlspecialchars($user['fname'] . ' ' . $user['lname']) . "</p>\n";
    echo "<p>Authorized: " . ($user['authorized'] ? 'Yes' : 'No') . "</p>\n";
    echo "<p>Active: " . ($user['active'] ? 'Yes' : 'No') . "</p>\n";
    echo "<p>Password Hash Length: " . strlen($user['password'] ?? '') . "</p>\n";
    echo "<p>Password Hash: " . htmlspecialchars(substr($user['password'] ?? '', 0, 20)) . "...</p>\n";
} else {
    echo "<p style='color: red;'>✗ User 'admin' not found</p>\n";
    exit;
}

// Test password verification
echo "<h3>3. Password Verification Test:</h3>\n";
$test_password = 'pass';

if (!empty($user['password'])) {
    if (password_verify($test_password, $user['password'])) {
        echo "<p style='color: green;'>✓ Password 'pass' is correct for user 'admin'</p>\n";
    } else {
        echo "<p style='color: red;'>✗ Password 'pass' is incorrect for user 'admin'</p>\n";
        
        // Let's try to create a new proper password hash
        echo "<h4>Creating new password hash:</h4>\n";
        $new_hash = password_hash($test_password, PASSWORD_DEFAULT);
        echo "<p>New hash: " . htmlspecialchars($new_hash) . "</p>\n";
        
        // Update the password in database
        $update_query = "UPDATE users_secure SET password = ? WHERE id = ?";
        $update_stmt = mysqli_prepare($connection, $update_query);
        mysqli_stmt_bind_param($update_stmt, 'si', $new_hash, $user['id']);
        
        if (mysqli_stmt_execute($update_stmt)) {
            echo "<p style='color: green;'>✓ Password updated successfully</p>\n";
            
            // Test again
            if (password_verify($test_password, $new_hash)) {
                echo "<p style='color: green;'>✓ New password verification successful</p>\n";
            } else {
                echo "<p style='color: red;'>✗ New password verification failed</p>\n";
            }
        } else {
            echo "<p style='color: red;'>✗ Failed to update password</p>\n";
        }
    }
} else {
    echo "<p style='color: red;'>✗ No password hash found in database</p>\n";
}

// Check configuration
echo "<h3>4. Configuration Check:</h3>\n";
echo "<p>Config value: " . (isset($config) ? $config : 'undefined') . "</p>\n";
if (isset($config) && $config == 1) {
    echo "<p style='color: green;'>✓ OpenEMR is configured</p>\n";
} else {
    echo "<p style='color: orange;'>⚠ OpenEMR configuration may be incomplete</p>\n";
}

mysqli_close($connection);

echo "<h3>5. Login Instructions:</h3>\n";
echo "<p><strong>Username:</strong> admin</p>\n";
echo "<p><strong>Password:</strong> pass</p>\n";
echo "<p><strong>URL:</strong> <a href='http://127.0.0.1:8080/interface/login/login.php'>http://127.0.0.1:8080/interface/login/login.php</a></p>\n";
?>