<?php
/*
 * Database Connection Test Script for OpenEMR
 * Generated by GitHub Copilot
 */

echo "<h2>OpenEMR Database Connection Test</h2>\n";
echo "<p>Testing database connection with current sqlconf.php settings...</p>\n";

// Load the current configuration
require_once(__DIR__ . '/sites/default/sqlconf.php');

echo "<h3>Configuration Values:</h3>\n";
echo "<ul>\n";
echo "<li><strong>Host:</strong> " . htmlspecialchars($host) . "</li>\n";
echo "<li><strong>Port:</strong> " . htmlspecialchars($port) . "</li>\n";
echo "<li><strong>Username:</strong> " . htmlspecialchars($login) . "</li>\n";
echo "<li><strong>Password:</strong> " . str_repeat('*', strlen($pass)) . " (length: " . strlen($pass) . ")</li>\n";
echo "<li><strong>Database:</strong> " . htmlspecialchars($dbase) . "</li>\n";
echo "<li><strong>Encoding:</strong> " . htmlspecialchars($db_encoding) . "</li>\n";
echo "</ul>\n";

echo "<h3>Connection Test Results:</h3>\n";

// Test 1: Check if mysqli extension is loaded
echo "<p><strong>1. Checking mysqli extension:</strong> ";
if (extension_loaded('mysqli')) {
    echo "<span style='color: green;'>✓ MySQLi extension is loaded</span></p>\n";
} else {
    echo "<span style='color: red;'>✗ MySQLi extension is NOT loaded</span></p>\n";
    echo "<p><strong>ERROR:</strong> The mysqli PHP extension is required but not installed.</p>\n";
    exit;
}

// Test 2: Attempt database connection
echo "<p><strong>2. Testing database connection:</strong></p>\n";

try {
    // Attempt connection
    $connection = @mysqli_connect($host, $login, $pass, $dbase, $port);
    
    if ($connection) {
        echo "<p style='color: green;'>✓ <strong>SUCCESS:</strong> Connected to database successfully!</p>\n";
        
        // Test database selection
        if (mysqli_select_db($connection, $dbase)) {
            echo "<p style='color: green;'>✓ Database '$dbase' selected successfully</p>\n";
            
            // Test a simple query
            $result = mysqli_query($connection, "SELECT VERSION() as version");
            if ($result) {
                $row = mysqli_fetch_assoc($result);
                echo "<p style='color: green;'>✓ MySQL Version: " . htmlspecialchars($row['version']) . "</p>\n";
                
                // Check if OpenEMR tables exist
                $result = mysqli_query($connection, "SHOW TABLES LIKE 'users'");
                if (mysqli_num_rows($result) > 0) {
                    echo "<p style='color: green;'>✓ OpenEMR 'users' table exists</p>\n";
                    
                    // Test user count
                    $result = mysqli_query($connection, "SELECT COUNT(*) as count FROM users");
                    if ($result) {
                        $row = mysqli_fetch_assoc($result);
                        echo "<p style='color: green;'>✓ Found " . $row['count'] . " users in database</p>\n";
                    }
                } else {
                    echo "<p style='color: orange;'>⚠ OpenEMR 'users' table not found - database may not be initialized</p>\n";
                }
            }
        } else {
            echo "<p style='color: red;'>✗ Failed to select database '$dbase'</p>\n";
        }
        
        mysqli_close($connection);
    } else {
        echo "<p style='color: red;'>✗ <strong>CONNECTION FAILED</strong></p>\n";
        echo "<p><strong>MySQL Error:</strong> " . htmlspecialchars(mysqli_connect_error()) . "</p>\n";
        echo "<p><strong>Error Number:</strong> " . mysqli_connect_errno() . "</p>\n";
    }
    
} catch (Exception $e) {
    echo "<p style='color: red;'>✗ <strong>EXCEPTION:</strong> " . htmlspecialchars($e->getMessage()) . "</p>\n";
}

echo "<h3>Troubleshooting Steps:</h3>\n";
echo "<ol>\n";
echo "<li><strong>Check MySQL Service:</strong> Ensure MySQL/MariaDB is running on the server</li>\n";
echo "<li><strong>Verify Credentials:</strong> Make sure the username 'admin' exists in MySQL with password 'Badger1234!'</li>\n";
echo "<li><strong>Check Permissions:</strong> Ensure the 'admin' user has proper permissions for the 'openemr' database</li>\n";
echo "<li><strong>Test Manual Connection:</strong> Try connecting manually: <code>mysql -h " . htmlspecialchars($host) . " -P " . htmlspecialchars($port) . " -u " . htmlspecialchars($login) . " -p</code></li>\n";
echo "<li><strong>Check Firewall:</strong> Ensure port " . htmlspecialchars($port) . " is not blocked</li>\n";
echo "</ol>\n";

echo "<h3>MySQL User Creation Commands:</h3>\n";
echo "<p>If the user doesn't exist, create it with these SQL commands:</p>\n";
echo "<pre style='background: #f4f4f4; padding: 10px; border-radius: 4px;'>\n";
echo "-- Connect as root user first\n";
echo "CREATE USER 'admin'@'localhost' IDENTIFIED BY 'Badger1234!';\n";
echo "GRANT ALL PRIVILEGES ON openemr.* TO 'admin'@'localhost';\n";
echo "FLUSH PRIVILEGES;\n";
echo "</pre>\n";
?>