<?php
/*
 * OpenEMR Login Process Simulation
 * Generated by GitHub Copilot
 * Tests the exact authentication process OpenEMR uses
 */

echo "=== OpenEMR Authentication Process Test ===\n\n";

// Simulate the exact login process
$site_id = 'default';
require_once("sites/$site_id/sqlconf.php");

$connection = mysqli_connect($host, $login, $pass, $dbase, $port);
if (!$connection) {
    die("Database connection failed: " . mysqli_connect_error() . "\n");
}

// Test the exact credentials being used
$test_username = 'admin';
$test_password = 'pass';

echo "Testing login process for:\n";
echo "Username: '$test_username'\n";
echo "Password: '$test_password'\n\n";

// Step 1: Check if user exists and is active (exactly like OpenEMR does)
$sql = "SELECT u.id, u.username, u.password, u.fname, u.lname, u.authorized, u.active, us.password as secure_password 
        FROM users u 
        LEFT JOIN users_secure us ON u.id = us.id 
        WHERE u.username = ? AND u.active = '1'";

$stmt = mysqli_prepare($connection, $sql);
mysqli_stmt_bind_param($stmt, 's', $test_username);
mysqli_stmt_execute($stmt);
$result = mysqli_stmt_get_result($stmt);

if ($user = mysqli_fetch_assoc($result)) {
    echo "✅ Step 1: User found in database\n";
    echo "   - User ID: " . $user['id'] . "\n";
    echo "   - Username: " . $user['username'] . "\n";
    echo "   - Active: " . $user['active'] . "\n";
    echo "   - Authorized: " . $user['authorized'] . "\n";
    echo "   - Has secure password: " . (!empty($user['secure_password']) ? 'Yes' : 'No') . "\n\n";
    
    // Step 2: Check password (OpenEMR's method)
    $stored_password = $user['secure_password'] ?: $user['password'];
    
    if (empty($stored_password)) {
        echo "❌ Step 2: No password found for user\n";
    } else {
        echo "✅ Step 2: Password found, verifying...\n";
        echo "   - Stored password hash: " . substr($stored_password, 0, 30) . "...\n";
        
        // Test password verification
        if (password_verify($test_password, $stored_password)) {
            echo "✅ Step 3: PASSWORD VERIFICATION SUCCESSFUL!\n";
            echo "✅ Authentication should work!\n\n";
            
            // Check authorization level
            if ($user['authorized'] == '1') {
                echo "✅ Step 4: User is authorized to access system\n";
            } else {
                echo "❌ Step 4: User is not authorized (authorized = " . $user['authorized'] . ")\n";
            }
            
        } else {
            echo "❌ Step 3: PASSWORD VERIFICATION FAILED!\n";
            echo "The stored hash does not match the password 'pass'\n\n";
            
            // Let's try to fix the password
            echo "Attempting to fix password...\n";
            $correct_hash = password_hash($test_password, PASSWORD_DEFAULT);
            
            $update_sql = "UPDATE users_secure SET password = ? WHERE id = ?";
            $update_stmt = mysqli_prepare($connection, $update_sql);
            mysqli_stmt_bind_param($update_stmt, 'si', $correct_hash, $user['id']);
            
            if (mysqli_stmt_execute($update_stmt)) {
                echo "✅ Password hash updated in database\n";
                echo "✅ Please try logging in again - it should work now!\n";
            } else {
                echo "❌ Failed to update password hash\n";
            }
        }
    }
    
} else {
    echo "❌ Step 1: User 'admin' not found or not active\n";
    
    // Let's see what users exist
    echo "\nChecking what users exist:\n";
    $check_sql = "SELECT username, active, authorized FROM users";
    $check_result = mysqli_query($connection, $check_sql);
    
    while ($row = mysqli_fetch_assoc($check_result)) {
        echo "- Username: " . $row['username'] . ", Active: " . $row['active'] . ", Authorized: " . $row['authorized'] . "\n";
    }
}

mysqli_close($connection);

echo "\n=== Try logging in again ===\n";
echo "URL: https://ddns.badgertechnologies.us/interface/login/login.php?site=default\n";
echo "Username: admin\n";
echo "Password: pass\n";
?>