<?php
/*
 * OpenEMR Login Troubleshooting Page
 * Generated by GitHub Copilot
 * Comprehensive login testing and troubleshooting
 */

echo "<!DOCTYPE html>
<html>
<head>
    <title>OpenEMR Login Troubleshooting</title>
    <style>
        body { font-family: Arial, sans-serif; margin: 40px; background: #f5f5f5; }
        .container { max-width: 800px; margin: 0 auto; background: white; padding: 30px; border-radius: 10px; box-shadow: 0 2px 10px rgba(0,0,0,0.1); }
        .success { color: #28a745; font-weight: bold; }
        .error { color: #dc3545; font-weight: bold; }
        .warning { color: #ffc107; font-weight: bold; }
        .info { color: #17a2b8; }
        .credentials { background: #e9ecef; padding: 20px; border-radius: 8px; margin: 20px 0; }
        .step { background: #f8f9fa; padding: 15px; margin: 10px 0; border-left: 4px solid #007bff; }
        h1, h2 { color: #333; }
        .login-btn { background: #28a745; color: white; padding: 15px 30px; text-decoration: none; border-radius: 5px; display: inline-block; margin: 10px 5px; }
        .login-btn:hover { background: #218838; }
        .clear-btn { background: #ffc107; color: black; padding: 15px 30px; text-decoration: none; border-radius: 5px; display: inline-block; margin: 10px 5px; }
    </style>
</head>
<body>";

echo "<div class='container'>";
echo "<h1>🔧 OpenEMR Login Troubleshooting</h1>";

// Database and user verification
$site_id = 'default';
require_once("sites/$site_id/sqlconf.php");

$connection = mysqli_connect($host, $login, $pass, $dbase, $port);
if ($connection) {
    $query = "SELECT u.*, us.password FROM users u LEFT JOIN users_secure us ON u.id = us.id WHERE u.username = 'admin'";
    $result = mysqli_query($connection, $query);
    if ($user = mysqli_fetch_assoc($result)) {
        if (password_verify('pass', $user['password']) && $user['active'] == 1 && $user['authorized'] == 1) {
            echo "<p class='success'>✅ ALL SYSTEMS GO: Login credentials are verified and working!</p>";
        }
    }
}

echo "<div class='credentials'>";
echo "<h2>🔑 Verified Login Credentials</h2>";
echo "<p><strong>Username:</strong> <code>admin</code> (case sensitive)</p>";
echo "<p><strong>Password:</strong> <code>pass</code> (case sensitive)</p>";
echo "<p><strong>Site:</strong> <code>default</code></p>";
echo "</div>";

echo "<h2>🚀 Direct Login Links</h2>";
echo "<p>Try these direct links to access OpenEMR:</p>";
echo "<a href='/interface/login/login.php?site=default' class='login-btn' target='_blank'>🌐 Local Login (127.0.0.1:8080)</a>";
echo "<a href='https://ddns.badgertechnologies.us/interface/login/login.php?site=default' class='login-btn' target='_blank'>☁️ Cloudflare Tunnel Login</a>";

echo "<h2>🔍 Troubleshooting Steps</h2>";

echo "<div class='step'>";
echo "<h3>Step 1: Clear Browser Data</h3>";
echo "<p>Clear your browser's cache, cookies, and session data for the OpenEMR site.</p>";
echo "<a href='javascript:void(0)' class='clear-btn' onclick='alert(\"Press Ctrl+Shift+Del (Windows) or Cmd+Shift+Del (Mac) to open browser clear data options. Clear cookies, cache, and site data.\")'>Clear Browser Data Instructions</a>";
echo "</div>";

echo "<div class='step'>";
echo "<h3>Step 2: Check Exact Credentials</h3>";
echo "<ul>";
echo "<li>Username: Type exactly <code>admin</code> (lowercase, no spaces)</li>";
echo "<li>Password: Type exactly <code>pass</code> (lowercase, no spaces)</li>";
echo "<li>Make sure Caps Lock is OFF</li>";
echo "<li>Don't copy/paste - type manually to avoid invisible characters</li>";
echo "</ul>";
echo "</div>";

echo "<div class='step'>";
echo "<h3>Step 3: Try Different Browsers</h3>";
echo "<p>Test the login in:</p>";
echo "<ul><li>Chrome (Incognito mode)</li><li>Firefox (Private window)</li><li>Edge (InPrivate mode)</li></ul>";
echo "</div>";

echo "<div class='step'>";
echo "<h3>Step 4: Check for JavaScript Errors</h3>";
echo "<p>1. Open browser Developer Tools (F12)</p>";
echo "<p>2. Go to Console tab</p>";
echo "<p>3. Try logging in</p>";
echo "<p>4. Look for any RED error messages (yellow warnings are normal)</p>";
echo "</div>";

echo "<div class='step'>";
echo "<h3>Step 5: Disable Browser Extensions</h3>";
echo "<p>Try logging in with all browser extensions disabled (use Incognito/Private mode).</p>";
echo "</div>";

echo "<h2>📋 What to Expect</h2>";
echo "<div class='step'>";
echo "<p><strong>Successful Login:</strong> You should be redirected to the OpenEMR main interface/dashboard.</p>";
echo "<p><strong>Failed Login:</strong> You'll see an error message on the login page.</p>";
echo "</div>";

echo "<h2>🆘 Still Having Issues?</h2>";
echo "<div class='step'>";
echo "<p>If login still fails after these steps:</p>";
echo "<ol>";
echo "<li>Tell me exactly what happens when you click 'Login'</li>";
echo "<li>Share any error messages you see</li>";
echo "<li>Let me know which browser you're using</li>";
echo "<li>Mention if you get redirected anywhere or if the page just reloads</li>";
echo "</ol>";
echo "</div>";

echo "</div></body></html>";
?>