tunnel: 74f3a7b9-44a1-47db-a975-744091eea32d
credentials-file: C:\Users\Administrator\.cloudflared\74f3a7b9-44a1-47db-a975-744091eea32d.json

ingress:
  - hostname: openemr.badgertechnologies.us
    service: http://127.0.0.1:8080
    originRequest:
      connectTimeout: 60s
      tlsTimeout: 30s
      tcpKeepAlive: 60s
      keepAliveConnections: 100
      keepAliveTimeout: 300s
      httpHostHeader: localhost:8080
  - service: http_status:404