<?php
/*
 * OpenEMR Simple Login Test
 * Generated by GitHub Copilot
 * Quick test to verify login credentials
 */

// Load OpenEMR configuration
$site_id = 'default';
require_once("sites/$site_id/sqlconf.php");

try {
    $connection = mysqli_connect($host, $login, $pass, $dbase, $port);
    if (!$connection) {
        die("Database connection failed: " . mysqli_connect_error());
    }

    // Test the admin user login
    $username = 'admin';
    $password = 'pass';
    
    $query = "SELECT u.id, u.username, u.authorized, u.active, us.password 
              FROM users u 
              LEFT JOIN users_secure us ON u.id = us.id 
              WHERE u.username = ? AND u.active = 1 AND u.authorized = 1";
    
    $stmt = mysqli_prepare($connection, $query);
    mysqli_stmt_bind_param($stmt, 's', $username);
    mysqli_stmt_execute($stmt);
    $result = mysqli_stmt_get_result($stmt);
    
    if ($user = mysqli_fetch_assoc($result)) {
        if (password_verify($password, $user['password'])) {
            echo "SUCCESS: Login credentials admin/pass are working correctly!\n";
            echo "User ID: " . $user['id'] . "\n";
            echo "Username: " . $user['username'] . "\n";
            echo "You can now log in to OpenEMR using:\n";
            echo "URL: http://127.0.0.1:8080/interface/login/login.php\n";
            echo "Username: admin\n";
            echo "Password: pass\n";
        } else {
            echo "ERROR: Password verification failed\n";
        }
    } else {
        echo "ERROR: User not found or not authorized\n";
    }
    
    mysqli_close($connection);
} catch (Exception $e) {
    echo "ERROR: " . $e->getMessage() . "\n";
}
?>