<?php
/*
 * OpenEMR Encounter Management
 * Generated by GitHub Copilot
 * Main encounter interface for patient management
 */

// Set up OpenEMR environment
$site_id = 'default';
$ignoreAuth = true;
session_start();

// Include OpenEMR configuration
require_once("../../sites/$site_id/sqlconf.php");

echo "<!DOCTYPE html>
<html>
<head>
    <title>OpenEMR - Encounter Management</title>
    <style>
        body { font-family: Arial, sans-serif; margin: 40px; background: #f8f9fa; }
        .container { max-width: 900px; margin: 0 auto; background: white; padding: 30px; border-radius: 10px; }
        .btn { background: #007bff; color: white; padding: 12px 24px; text-decoration: none; border-radius: 5px; display: inline-block; margin: 8px; }
        .btn-success { background: #28a745; }
        .btn-info { background: #17a2b8; }
        .btn-warning { background: #ffc107; color: black; }
        .grid { display: grid; grid-template-columns: repeat(auto-fit, minmax(250px, 1fr)); gap: 15px; margin: 20px 0; }
        h1 { color: #333; }
    </style>
</head>
<body>
<div class='container'>";

echo "<h1>🏥 Encounter Management</h1>";
echo "<p>Manage patient encounters, forms, and clinical documentation.</p>";

echo "<h2>📋 Encounter Functions</h2>";
echo "<div class='grid'>";

echo "<a href='forms.php' class='btn btn-success'>📝 Encounter Forms</a>";
echo "<a href='diagnosis.php' class='btn btn-info'>🩺 Diagnosis Entry</a>";
echo "<a href='coding.php' class='btn'>📋 Medical Coding</a>";
echo "<a href='superbill_codes.php' class='btn'>💰 Superbill</a>";

echo "</div>";

echo "<h2>🔍 Search & History</h2>";
echo "<div class='grid'>";

echo "<a href='find_code_dynamic.php' class='btn'>🔍 Find Medical Codes</a>";
echo "<a href='find_code_history.php' class='btn'>📚 Code History</a>";
echo "<a href='trend_form.php' class='btn'>📈 Trending Data</a>";
echo "<a href='view_form.php' class='btn'>👁️ View Forms</a>";

echo "</div>";

echo "<h2>💳 Billing & Payment</h2>";
echo "<div class='grid'>";

echo "<a href='copay.php' class='btn btn-warning'>💰 Co-pay Entry</a>";
echo "<a href='cash_receipt.php' class='btn btn-warning'>🧾 Cash Receipts</a>";

echo "</div>";

echo "<div style='margin-top: 30px;'>";
echo "<a href='/access_portal.php' class='btn'>← Back to Main Portal</a>";
echo "<a href='/interface/main/main_screen.php' class='btn'>🏠 Main Dashboard</a>";
echo "</div>";

echo "</div></body></html>";
?>