<?php
/*
 * Auto Billing Hook Integration
 * Generated by GitHub Copilot
 * 
 * This modifies OpenEMR's appointment status update process to trigger
 * automatic insurance billing on checkout
 */

require_once("../globals.php");
require_once("$srcdir/../library/auto_billing.php");

/**
 * Enhanced appointment status update with auto billing
 * This replaces or extends the existing status update functionality
 */
function update_appointment_status_with_auto_billing($event_id, $new_status) {
    
    // First, update the appointment status normally
    $update_sql = "UPDATE openemr_postcalendar_events SET pc_apptstatus = ? WHERE pc_eid = ?";
    $result = sqlStatement($update_sql, array($new_status, $event_id));
    
    if ($result) {
        // Get appointment details
        $appointment = sqlQuery("SELECT pc_pid, pc_eventDate, pc_apptstatus FROM openemr_postcalendar_events WHERE pc_eid = ?", array($event_id));
        
        if ($appointment) {
            $patient_id = $appointment['pc_pid'];
            
            // Log the status change
            error_log("Appointment Status Change: Event $event_id, Patient $patient_id, New Status: $new_status");
            
            // Trigger auto billing hook
            $billing_result = handle_appointment_status_change($event_id, $new_status, $patient_id);
            
            if ($billing_result) {
                // Add success message to session for user feedback
                if (session_status() == PHP_SESSION_ACTIVE) {
                    $_SESSION['auto_billing_message'] = "Appointment checked out and insurance claim automatically submitted.";
                }
            }
            
            return true;
        }
    }
    
    return false;
}

/**
 * AJAX handler for appointment status updates
 * This can be called via AJAX to update status and trigger auto billing
 */
if (isset($_POST['action']) && $_POST['action'] == 'update_status') {
    
    $event_id = isset($_POST['event_id']) ? (int)$_POST['event_id'] : 0;
    $new_status = isset($_POST['status']) ? $_POST['status'] : '';
    
    if ($event_id && $new_status) {
        
        // Verify user has permission
        if (!acl_check('patients', 'appt')) {
            http_response_code(403);
            echo json_encode(array('success' => false, 'message' => 'Access denied'));
            exit;
        }
        
        $success = update_appointment_status_with_auto_billing($event_id, $new_status);
        
        $response = array(
            'success' => $success,
            'message' => $success ? 'Status updated successfully' : 'Failed to update status'
        );
        
        // Add auto billing message if available
        if (isset($_SESSION['auto_billing_message'])) {
            $response['auto_billing'] = $_SESSION['auto_billing_message'];
            unset($_SESSION['auto_billing_message']);
        }
        
        header('Content-Type: application/json');
        echo json_encode($response);
        exit;
    }
}

/* END AI-GENERATED CODE */
?>